In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("Social_Network_Ads.csv")

In [3]:
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [24]:
df.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [4]:
X = df[['Age','EstimatedSalary']]
y = df['Purchased']

In [5]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.25)

In [6]:
X_train.shape

(300, 2)

In [7]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [8]:
model.score(X_test, y_test)

0.64

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)

MinMaxScaler()

In [12]:
MinMaxScaler()

MinMaxScaler()

In [13]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [14]:
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [15]:
model.score(X_test_scaled, y_test)

0.84

In [16]:

X_train_scaled[0:10]

array([[0.61904762, 0.17777778],
       [0.0952381 , 0.48888889],
       [0.66666667, 0.32592593],
       [0.64285714, 0.22222222],
       [0.85714286, 0.40740741],
       [0.64285714, 0.08148148],
       [0.4047619 , 0.03703704],
       [0.04761905, 0.15555556],
       [0.04761905, 0.4962963 ],
       [0.19047619, 0.48148148]])

In [17]:
from sklearn.metrics import confusion_matrix

In [18]:
y_p = model.predict(X_test_scaled)
y_p

array([1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [19]:
confusion_matrix(y_test,y_p)

array([[61,  3],
       [13, 23]], dtype=int64)

In [20]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test,y_p)
acc

0.84

In [21]:
err = 1 - acc
err

0.16000000000000003

In [22]:
from sklearn.metrics import precision_score

prec = precision_score(y_test, y_p)
prec

0.8846153846153846

In [23]:
from sklearn.metrics import recall_score

rec = recall_score(y_test, y_p)
rec

0.6388888888888888